version: "3.4"

services:

  rappel:
    build:
      dockerfile: ./docker/rappel.dockerfile
      context: ./
    environment:
      DISPLAY: host.docker.internal:0
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    volumes:
      - type: bind
        source: ./
        target: /rappel
        # there is a mix/rebar3 problem so we need a local install of LFE
      - type: bind
        source: ../lfe
        target: /lfe      # when you are developing and you want to local mount the pometo APL code
      - type: bind
        source: ../pometo
        target: /pometo
      # for xwindows
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
